version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 362520992479.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=362520992479.dkr.ecr.us-east-1.amazonaws.com/diatoz_reg
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - ls
      - docker --version
      - docker build -t diatoz_reg .
      - docker tag diatoz_reg:latest 362520992479.dkr.ecr.us-east-1.amazonaws.com/diatoz_reg:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo pushing to repo
      - docker push 362520992479.dkr.ecr.us-east-1.amazonaws.com/diatoz_reg:latest
      - echo Writing image definitions file...
      - DOCKER_CONTAINER_NAME=diatoz_reg

artifacts:
  files:
    - '**/*'
